### ISSUE TITLE
dist directory only contains to_csv.*

### ISSUE THREAD

**Issue by Steve-Mcl** [StoneCypher/csv_by_rfc#25]
I would like to use this lib in a node project.

I have already raised #23 as one part of the issue however, I wish to also use the `from_csv` code but it is not copied to the dist folder.

additionally, the package.json `main` entry point points to `index.js` but that does NOT exist. This should be either `dist/index.js` or the output of your npm package should be adjusted to publish the dist files to the root of the package.

**Comment by StoneCypher** [comment]
quite right, how embarrassing

as you can see i was building this up for a cli thing that day

now that i know someone wants to use this, lemme set up ci and autopublish real quick too

this is now fixed - to_csv and index are now in the relevant dist directory, and the index is pointed to correctly

this will be changed again in a moment as i do the bundling dance
